### ISSUE TITLE
davwheat/whisper

### ISSUE THREAD

**Issue by Profi420** [Free-Flarum/freeflarum.com#370] opened 2022-06-28 15:43 UTC
__Packagist URL for extension:__
https://github.com/davwheat/whisper

__Why should we install the extension?__
Since Whisper is not working fine: There is a Fork for it. Would be great to enable this.
https://discuss.flarum.org/d/30933-who-could-fix-pm-for-flarum/14

**Comment by CWKevo** [comment] 2022-06-29 11:10
Duplicate of #365

**Closed** 2022-06-29 11:10 UTC
Labels: 📄📄  Duplicate, 🙋 Extension/feature request
