### ISSUE TITLE
Mailling by Clarkwinkelmann (To be deleted - Accidently made a topic similar to existant one. )

### ISSUE THREAD

**Issue by shawny43** [Free-Flarum/freeflarum.com#377] opened 2022-07-25 02:03 UTC
## Packagist URL for extension:

https://packagist.org/packages/clarkwinkelmann/flarum-ext-mailing

## Why should this extension be installed?

Mass mailing and individual mailing. Mods can mail user about their ban if needed.

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum. Does not apply to extension updates or "re-installations".
---

**Comment by CWKevo** [comment] 2022-07-25 04:15
Indeed, duplicate of #308

**Closed by CWKevo** 2022-07-25 04:15 UTC
Labels: 🙋 Extension/feature request
